### ISSUE TITLE
CallOptions with direct headers assigment throws exception

### ISSUE THREAD

**Issue by StefH** [protobuf-net/protobuf-net.Grpc#111]
1. Using this code throws an exception.
``` c#
var options = new CallOptions
{
  Headers = { { "Authorization", $"Bearer abc" } }
};
```

2. This code works fine:
``` c#
var headers = new Metadata
{
  { "Authorization", $"Bearer abc" }
};
var options = new CallOptions(headers);
```

**Comment by mgravell** [comment]
The code in question is all from `Grpc.Core.Api`, so: if anything this would be a question for https://github.com/grpc/grpc - however! I don't think the code from `1` can ever work, because `CallOptions` is a `struct`, and `struct`s should almost always be immutable; when you create a `struct` with the default constructor like this, the metadata will forever be `null`, and even if it were possible to inject the constructor, it would be undesirable to create an instance "just in case". However! Perhaps what you're after is:

``` c#
var options = new CallOptions(new Metadata {
    { "Authorization", $"Bearer abc" }
});
```

which works correctly

**Comment by StefH** [comment]
OK. Thanks for the detailed answer,
