### ISSUE TITLE
Does byte[] has to be 32 multiple?

### ISSUE THREAD

**Issue by victoriorinescu** [protobuf-net/protobuf-net.Grpc#123]
I have something like:

class MyClass
{
…
public byte[] Data {get;set;} = new byte[16];
...
}

I checked on the client, before the call I have 16 bytes; on the server I received a 32 byte array with the first 16 bytes containing the data from the client and the next 16 set to 0; I tried with 20bytes - still 32 bytes received and the last 12=0.

So, does byte[] has to be 32 multiple and if not it is padded with 0?

**Comment by mgravell** [comment]
K, what's happening here is that protobuf-net is trying to observe the "concat === merge" semantics from protobuf; the problem here is that your *initializer* is starting the data with 16 bytes, and then it is applying the *extra* ones, which at one point meant: "concat". I need to re-evaluate that vs the Google implementation, but right now there are simple fixes:

1. you can add `OverwriteList = true` on the `[ProtoMember(...)]` marker, which tells it to never use concat rules, or
2. you can add `SkipConstructor = true` on the `[ProtoContract(...)]` marker, which tells it to not execute your initializer

Any use?

**Comment by victoriorinescu** [comment]
I couldn't apply second fix because I needed the constructor, but the first fix worked.
10x.

**Comment by FrankSzendzielarz** [comment]
Goddammit....is this really the error? :-) I have been negotiating with Claude AI trying to work out what this is. So client side deserialisation tries to concatenate into target values rather than set?

 OverwriteList = true. If this works I am moving to DeepSeek
