### ISSUE TITLE
Upgrade to protobuf-net 3.0

### ISSUE THREAD

**Issue by Ilchert** [protobuf-net/protobuf-net.Grpc#125]
Hello! 
Are you going to upgrade protobuf-net reference to the latest version? Or you will keep compatibility with 2.0.
Thanks!

**Comment by mgravell** [comment]
The decision to target v2 is very deliberate, because there are some changes in behaviour between v2 and v3 that I do not desire to *force* on people; however, protobuf-net.Grpc is entirely compatible with v3, and knows how to use the more advanced features (such as "pipelines" APIs) that are only implemented in v3. So: if you want to use v3 - that's fine: just add an explicit package-reference to protobuf-net v3, rather than simply taking the transitive v2 dependency.

**Comment by Ilchert** [comment]
Thanks!

**Comment by virzak** [comment]
One issue I found with this is that v2 references `System.ServiceModel.Primitives` which ends up being a part of the deployment. It adds 1,846 KB System.Private.ServiceModel.dll file, which is larger than protobuf-net.*.dll combined. It takes a little bit of digging to find where it is coming from. And that's if you're lucky enough to notice that you have extra assemblies in `bin\Release\net5.0\runtimes\win\lib\netstandard2.0` folder. Chances are you [won't](https://github.com/grpc/grpc-dotnet/blob/6fd69504c7ad4496a04c77e643e222507fb0846f/examples/Coder/Server/Server.csproj#L10) be.

Once I found this issue, I got it resolved, but perhaps it is a good idea to encourage new users to add v3 in the Getting Started?
