### ISSUE TITLE
streaming an IObservable

### ISSUE THREAD

**Issue by apobekiaris** [protobuf-net/protobuf-net.Grpc#14]
using grpc with a proto file as per asp.net docs i wrote
```
service Dispatcher {

	rpc RequestEvent (Request) returns (stream Event) {}

```

the grpc tools generate the service which I then integrate to the existing observables in my system like  

```cs
 internal class DispatcherImpl : Dispatcher.Dispatcher.DispatcherBase{
        
        public override async Task RequestEvent(Request request, IServerStreamWriter<Event> responseStream, ServerCallContext context){
  
                
                await SomeController.Observable
                    .ForEachAsync(value =>
                        {
                            responseStream.WriteAsync(value).Wait();
                        }, 
                        context.CancellationToken);


        }
```
this pretty much works ok, but I would like to send .net types and share them and avoid the `build hack` so I came here. However all your samples use the IAsyncEnumerable, although you mentioned that Task is also possible. So, can you provide an example based on your `TimeService` perhaps that streams an IObservable?

**Comment by mgravell** [comment]
> However all your samples use the IAsyncEnumerable,

Right now, `IAsyncEnumerable` is how protobuf-net.Grpc sees `stream`; additional APIs may be possible in theory, but that's the primary API anticipated

> although you mentioned that Task is also possible

Can you be more specific as to the context there? I can't give you a `[Value]Task<List<T>>`, for example - the entire point of a `stream` is that it is an *open* sequence, and blocking an open sequence is anathema. You mention `IObservable` - "reactive" is indeed a very similar and alternative model; it *isn't* once I've touched so far, but I could *absolutely* be agreeable to that shape of API; however, isn't the point of IObservable that it is *similar to a sequence* (push instead of pull), so surely it would be a *single* observable, not a sequence?

**Comment by apobekiaris** [comment]
>Can you be more specific as to the context there? 

quote from docs: We’re using ValueTask<T> here, but the library also supports Task<T>

```cs
await SomeController.Observable
                    .ForEachAsync(value =>
                        {
                            responseStream.WriteAsync(value).Wait();
                        }, 
                        context.CancellationToken);
````

what happens above while we are on traditional .net grpc is: I await for an observable that never completes and for each emit i send to the wire.

>Right now, IAsyncEnumerable is how protobuf-net.Grpc sees stream

how does this happen? can i directly write to the stream as above? having a Task as a return type?

**Comment by mgravell** [comment]
> quote from docs: We’re using ValueTask here, but the library also supports Task

Yes, and that's for unary responses; so:

- "sending one thing" - take `Foo` as a parameter
- "returning one thing" - use `Foo`, `Task<Foo>` or `ValueTask<Foo>` as the return type
- "sending multiple things" - take `IAsyncEnumerable<Foo>` as a parameter
- "returning multiple things" - use `IAsyncEnumerable<Foo>` as the return type

The library then works to switch between `IAsyncEnumerable<T>` and the underlying Grpc.Api api.

So: if we wanted to support another pattern - `IObservable<T>` - there are various ways we could look at doing this:

1. we write a bunch more code to explicitly support `IObservable<T>` internally *talking directly to the gRPC layer* (like how `IAsyncEnumerable<T>` works)
2. we write helper methods to let the caller switch between universes, example shown below
3. we automate option 2 *inside* the library, so it is still indirect, but the caller doesn't need to know about it
4. we provide a streaming abstraction (ideally separate from the Grpc.Api abstraction) that could be used as a base for a range of such patterns, if that makes sense

possible example:

``` c#
IObserver<Foo> mySource = ...;
IObserver<Bar> myResult = proxy.DoSomething(mySource.AsAsyncEnumerable()).AsObservable();
```

where `AsAsyncEnumerable` and `AsObservable` are the shim methods we'd add to flip/flop between the worlds.

> how does this happen

as a library implementation detail

>  can i directly write to the stream as above?

Not today, although we could perhaps in the future, if we figure out what the scenarios and API for that are

**Comment by adams85** [comment]
Hi, Marc!

First of all, I'd like to say thanks for your amazing work you shared with us. I've been using your libs with great results.

Your code-first Grpc solution works like a charm as well. There's only one thing that feels a bit off for me: what's discussed in this issue.

I think `IObservable<T>` would be the natural choice for streaming instead of `IAsyncEnumerable<T>`. My problem with the latter is that it has a pull nature. Converting an observable to an async enumerable involves queuing inevitably. (E.g. see [the implementation](https://github.com/dotnet/reactive/blob/master/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToAsyncEnumerable.Observable.cs) of ReactiveX). In contrast, converting an async enumerable to observable is trivial (e.g. see [this implementation](https://github.com/dotnet/reactive/blob/master/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs)).

So I think option 3 would be the best solution, only the lib should use a push-based model internally. If a consumer needed `IAsyncEnumerable<T>`, it could be easily produced by wrapping the underlying `IObservable<T>`. Thus, the backward compatibility would be guaranteed and consumers would also have the choice to use observables directly in their services.

What's your opinion on this? Is there any ongoing effort to solve this? I might take a stab at it if you don't mind. (I haven't looked at the internals yet, I'm not sure how big task it'd be, so I cannot promise it for sure at the moment.)

**Comment by mgravell** [comment]
@adams85 happy to explore it; now, as I see it, this only makes sense for the *parameter* part, i.e. the `foo` in either of:

``` c#
TResult ClientStreaming(IAsyncEnumerable<T> foo, ... optional ctx);
IAsyncEnumerable<TResult> Duplex(IAsyncEnumerable<T> foo, ... optional ctx);
```

(we can discuss whether or not it makes sense for the result, but let's just explore this first)

One of the main problems, as I see it, is that we are faced with a huge challenge because of the different threading models in play here. `IObservable<T>`/`IObserver<T>` is fundamentally synchronous in nature, and `IAsyncEnumerable<T>` is fundamentally asynchronous in nature. The underlying gRPC transports that I have to play with: also, fundamentally asynchronous in nature.

As such, we need to think about how we cross that gap. There are two sets of problems:

1. at the client, we need to think about what we would do in `OnNext` if `WriteAsync` (on the underlying transport) is not complete; even if we stash a "thing in progress task", we are still just kicking the can down the road, and *at some point* we're going to have to bite the bullet and say `.Wait()` - aka "sync over async", which is a **really, really bad idea**
2. at the server, we have the opposite problem: triggering `OnNext` from the async reader is trivial, but now the consumer ("your" code, for a generic "you") is forced to be purely synchronous - you have no mechanism to indicate a future completion

These are both things I'd ideally like to avoid, but *if we think purely in terms of `IObservable<T>`/`IObserver<T>`: I don't think we can.

Now; this might just be me missing something about `IObservable<T>`/`IObserver<T>`, and I'm happy to get more input.

---

Maybe, instead of focusing on a specific technology, we should take a step back and look at *what you want to do*. First, let me play back my current understanding; it doesn't seem hugely controversial: you simply want to have a "push" API rather than a "pull" API. If I've misunderstood that, and actually you're fundamentally attached to `IObserable<T>` (presumably because you have code that uses that - which is fine, I get that), then let me know! but: let me run ahead with my assumption. Furthermore, you don't want buffering. And I'm asserting that we *should* care about async as the forwards model.

Let's imagine some hypothetical API where you could pass *something* (we can worry about the "what" later); would some notional pair like:

``` c#
public ValueTask<bool> PushAsync(T value, CancellationToken cancellationToken = default);
public bool TryComplete(Exception? error = null)
```

expose what you want? Note this sounds a lot like `Channel<T>`, except with reduced complexity and zero buffering - I'm thinking more like a "push API for enumerators".

**Comment by mgravell** [comment]
@adams85 I explored some ideas in a branch as above; includes usage demo [here](https://github.com/protobuf-net/protobuf-net.Grpc/commit/99f2e49b2fbcf3eb2007996c050dc589b20cb320#diff-3ddbe6f2f573dfe225999dc1fa4ac690R226-R235)

**Comment by mgravell** [comment]
@JuliusSweetland this might also be of interest to you ^^^

**Comment by adams85** [comment]
@mgravell Digesting your remarks and giving some more thought to the problem, I came to the conclusion that I was simply wrong (well, at least, partially right) when I stated "`IObservable<T>` would be the natural choice for streaming".

Stepping back and looking at the bigger picture, I realized that we're dealing here with a producer/consumer problem. Considering the *parameter part*, the client is the producer and the server is the consumer. Speaking about the *result*, it's the other way round.

`IObservable<T>` would make perfect sense for the consumer side. When a message arrives, we'd just need to invoke the `OnNext` handlers of the subscribed observers. (Of course, we should insert something like an `ObserveOn` call into the chain because the observers' synchronous handlers shouldn't block the receiving of subsequent messages.) When observers don't care any more, they can signal that by disposing their subscription (the disposable object returned by `Subscribe`). I'm not completely sure what you mean by "you have no mechanism to indicate a future completion" but probably this answers it.

However, things on the producer side aren't that smooth. We have a dilemma here. Either we let the source sequence to produce items at its own rate, but then we need to introduce some kind of queuing (buffering) necessarily. Or we make the source sequence wait for delivery (`WriteAsync`), in other words, we block the production of items (that is, slow it down to match the rate of delivery). On top of that, we could only achieve blocking, as you mentioned, by "sync over async" which is a recipe for disaster. Unortunately, all this makes my original concept void.

So, if my understanding is correct, even the push API you proposed cannot solve this completely. It would eliminate "sync over async" for sure but it still wouldn't resolve the dilemma described above. It could be useful in situations where one can live with blocking of the source sequence but as for my actual use case it's out of the question. Luckily, with the help of Ix.NET we can easily introduce the necessary buffering and switch between the two worlds.

**Comment by mgravell** [comment]
Well here's the thing: via `IAsyncEnumerable<T>` we have no dilemma. If you want buffering: `Channel<T>` is suitable - allows control over size (bounded, unbounded), threading models, etc, and there's a custom `AsAsyncEnumerable` method in the library that allows you to get the optimal cancellation behavior.  If you don't want buffering: maybe the `PushAsyncEnumerable` approach I've toyed with here gives you what you need. And: zero changes to the core logic (just: some interesting implementations of `IAsyncEnumerable<T>`)

**Comment by adams85** [comment]
Don't get me wrong, I'd been able to solve the push/pull issue using Ix.NET, I just thought that this was an area where your lib could be improved using `IObservable<T>`. Now I see that the current API as good as it gets, so I'm perfectly happy with it. :)

Indeed, channels can also be used as an alternative to Ix.NET when more control is needed. Thank you for pointing that out. Also thanks for spending time on exploring this idea.

**Comment by codeputer** [comment]
i'm learning here - lx.net ? I know reactive from awhile back - is this new? Link?

**Comment by JuliusSweetland** [comment]
It's part of the reactive library. Rx = Reactive extensions

Ix = IEnumerable extensions

**Comment by mgravell** [comment]
I think the best bet here is to leave this alone in the core library; if extensions want to *wrap around this*, fine - but I'm pretty happy that for now we should stick with just `IAsyncEnumerable<T>` as the streaming metaphor
