### ISSUE TITLE
OperationCanceledException does not propagate CancellationToken

### ISSUE THREAD

**Issue by hakenr** [protobuf-net/protobuf-net.Grpc#162]
Currently, when using the gRPC client, you are unable to catch `OperationCanceledException` with `CancellationToken` checking:
```csharp
try
{
  await grpcClient.DoSomething(cancellationToken);
}
catch (OperationFailedException ex) when (ex.CancellationToken = cancellationToken)
{
  // not being catched if the when-clause is there
}
```
The when-clause pattern is present in Blazor: https://github.com/dotnet/aspnetcore/blob/bbe143d870f27932ec8fa749108ebe0ec3eba362/src/Components/Web/src/Virtualization/Virtualize.cs#L364

Recommended best practice: https://devblogs.microsoft.com/premier-developer/recommended-patterns-for-cancellationtoken/

Is there any chance to pass the CancellationToken to the OperationCanceledException?

**Comment by hakenr** [comment]
(Not sure if it is not from the underlying Grpc.Core)

**Comment by hakenr** [comment]
It seem the stack is not throwing OperationCanceledException at all, it remains wrapped as RpcException with status Cancelled?
https://github.com/protobuf-net/protobuf-net.Grpc/blob/3550147281b2de4fc0d7f0ed05d140e79b5b3ecc/examples/wcf-port/SimpleStockTicker/src/TraderSys.SimpleStockTickerServer.ClientConsole/Program.cs#L41-L51

**Comment by mgravell** [comment]
We are a little restricted in terms of what gRPC exposes to us; we *could* potentially check for `RpcException` with a cancellation status, but that would be an API change *and* would potentially make it harder to access the details that *are* exposed on `RpcException`. I'm not sure it is a good change to make, to be honest. I also doubt we could correctly know the cancellation source, in terms of setting `ex.CancellationToken` correctly, because *we aren't the ones triggering the cancellation* - it is coming from the Google or Microsoft transport.

**Comment by hakenr** [comment]
There is the `RpcException.Status.DebugException` which usually gets populated for client-side exceptions. Is there any chance to add the original `OperationCanceledException` (possibly with `CancellationToken`) there?

**Comment by mgravell** [comment]
It isn't "us" that raises `RpcException`, so: while that is a fair question, it is probably one for grpc/grpc (Google) or grpc/grpc-dotnet (Microsoft)

**Comment by mgravell** [comment]
I've fixed the *one* case where we throw our own `RpcException` to expose the original exception (annoyingly, as .Status.DebugException, but... it is what it is); I think that's all I can do
