### ISSUE TITLE
IsReference in DataContracts is ignored

### ISSUE THREAD

**Issue by KaNarlist** [protobuf-net/protobuf-net.Grpc#214]
Hi,

coming from WCF I noticed, that IsReference=true in DataContracts has no effect when using protobuf-net. AFAIK GRPC or PROTOBUF don't support referencing in its messages, but it's something we need.

So if for example you have a class A with a member of class B and a service method returns two instances of class A that both have the same instance of class B as a member, on the client B needs to be a single instance too, instead of two different ones with the same data.

Would it be possible to include this into protobuf-net, so it works if you have a pure protobuf-net client and server situation?
My gut tells me no, but I'm not sure who exactly is responsible for (de)seriliazation and how flexible the PROTOBUF protocol is.

**Comment by mgravell** [comment]
Right. So: the underlying protobuf specification has no concept that could help with this. We faked it in protobuf-net V2, available via the protobuf-net specific attributes, but: it had rough edges and ways to shoot yourself in the foot, and was annoyingly complex. It is a feature that is now deprecated in V3, unless somebody does a much better job of finding reasons to reinstate it than I have personally managed to date. My advice would be "don't do that" - instead fine other ways of representing the intend via data instead of structure. Remember: your serialization model doesn't need to be your domain model.

**Comment by KaNarlist** [comment]
Unfortunately the domain model is a rather old and ugly one we had to take as it was. Refactoring the application now, to use a different model for serialization would mean a huge effort. I'll guess I have to take a look at WCF Core as an alternative :\
