### ISSUE TITLE
Specified method is not supported

### ISSUE THREAD

**Issue by ali-zfr** [protobuf-net/protobuf-net.Grpc#254]
I am trying to call grpc server that implements code first service. I am unable to call that service from client if I add **CallOptions** to the service method parameters for **passing bearer token**.

When I execute the client it throws the following exception:

> 
Unhandled exception. System.NotSupportedException: Specified method is not supported. at ProtoBuf.Grpc.Internal.Proxies.ClientBase.ICustomerService_Proxy_0.ICustomerService.CreateCustomer(CreateCustomerCommand , CallOptions )

If I remove the CallOptions parameter and then execute the call it works perfectly as it should.

_Additionally, package referenced in client and server have the same version._

**Service Implementation**
```
    [Authorize]
    public class CustomerService : ICustomerService
    {
        IMediator _mediator;
        public CustomerService(IMediator mediator)
        {
            _mediator = mediator;
        }

        public Task CreateCustomer(CreateCustomerCommand request, CallOptions callOptions)
        {
            return _mediator.Send(request);
        }
    }
```

**Comment by mgravell** [comment]
short version: use `CallContext`, not `CallOptions`; `CallContext` *has* a `.CallOptions`, or many of the expected features are directly available (for example, `.RequestHeaders`, `.CancellationToken`, etc)

longer version: protobuf-net.Grpc, being code-first, attempts to unify the client and server APIs so that the same interface (presumably `ICustomerService` in this case) makes sense for both the client and server side. This is not possible with `CallOptions` vs `ServerCallContext`, so protobuf-net.Grpc creates `CallContext` which bridges the gap between both

**Comment by ali-zfr** [comment]
thanks @mgravell  that worked.

One more thing I would like to ask. Why is it that a grpc service running on kestrel works perfectly fine but a service running on IIS throws unexpected errors?

**Comment by mgravell** [comment]
If you don't tell me exactly what unexpected errors it is throwing, I can't really comment - but my first guess would be "is http/2 configured? can IIS even use http/2?"

**Comment by mgravell** [comment]
Ultimately, protobuf-net.Grpc doesn't handle these details itself - it simply sits on top of the transport provided either by Google (Grpc.Core) or Microsoft (Grpc.AspNetCore, for the server); I don't know all the details of what happens internally. I would first say:

"if you create a very basic hello-world service using the vanilla .proto-first experience: does *that* work?"

If that doesn't work: protobuf-net.Grpc doesn't stand a chance, as the problem is at a layer below, that we don't maintain or support. If it *does* work: I can happily step in to try to investigate the difference.

**Comment by menaheme** [comment]
Http2 requires https , is iis binding configuration in place for that?

**Comment by mgravell** [comment]
@menaheme nit: that's not exactly true; http/2 definitely *recommends* TLS, but it can work without. Kestrel has problems trying to support H1 and H2 on the same port without TLS, and if you're saying "H2 inside IIS specifically: requires TLS", then: I would readily believe you.

**Comment by menaheme** [comment]
Yes thats what i meant, iis will not by deafault allow http2 without tls

**Comment by ali-zfr** [comment]
I actually had a https binding for the service added. I tried to make a client request to simple contract first application but that too 
 failed.
