### ISSUE TITLE
Assembly Version not matching Nuget Package version.

### ISSUE THREAD

**Issue by Liam-M-Patterson** [protobuf-net/protobuf-net.Grpc#333]
I encountered this issue recently when trying to update the dependencies in my app. I noticed that the assembly version of the protobuf-net packages does not match the version on Nuget. This leads to some misleading behaviour where it can be difficult to determine exactly which version of protobuf an application is using. In Visual Studio, I have updated all of my application packages to use the latest protobuf-net packages I need. protobuf-net 3.2.30, protobuf-net.Core 3.2.30 and protobuf-net.Grpc 1.1.1. The packages download from nuget just fine. If I let my application run with the automatic assmebly redirects turned on, it seems to work, but I noticed that in the app.config there is a redirect for protobuf-net to target version 3.0.0.0, even though the PackageReference is for 3.2.30. Inspecting the nuget packages folder there is a sub directory for version 3.2.30 with the correct target frameworks installed. Inspecting the properties on the protobuf-net.dll it appears that the file is version 3.2.30.709. and appears correct. However if I try to change the assembly redirect to target this version the app does not work, and I get numerous runtime errors where protobuf-net cannot find the assembly it is looking for. Additionally, when I try to load the actual dll file and see the version I notice that the assembly itself is versioned at 3.0.0.0, not 3.2.30.X. 

`([system.reflection.assembly]::loadfile("C:\..\3rdParty\nugetPackages\protobuf-net.grpc\1.1.1\lib\net6.0\protobuf-net.Grpc.dll")).FullName`

`protobuf-net.Grpc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67`

If I run the above command in a powershell or windows terminal I get the following output. Note that you have to provide the absolute path to the dll, and the above command will not work as is until that is changed.

My question is, is this intentional behaviour for the protobuf-net package? This seems to be contradictory to how most other packages handle the versioning.

**Comment by mgravell** [comment]
Yes, this is intentional. It is pretty normal to pin the assembly version - at *least* pinned for "majors", and often also pinned for "minor". This is because otherwise there are *significant* implications re assembly binding redirect requirements on .NET Framework. The real assembly version is available in extended metadata.

**Comment by menaheme** [comment]
Very interesting!
Can you please elaborate a bit?

**Comment by mgravell** [comment]
First, some examples, taken from nuget.org most common downloads, sorting by downloads descending, then investigating the assemblies via nuget package explorer:

- [Newtonsoft.Json](https://nuget.info/packages/Newtonsoft.Json/13.0.3) - package 13.0.3, Full Name:Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
- [Microsoft.Extensions.DependencyInjection](https://nuget.info/packages/Microsoft.Extensions.DependencyInjection/6.0.1) - package 6.0.1 (deliberately finding the first non-0.0), Full Name:Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
- [Serilog](https://nuget.info/packages/Serilog/3.1.1) - package 3.1.1, Full Name:Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10

The short version of "why" is that on .NET Framework, every time this changes, it causes a problem if the library version requested isn't *exactly* what is received; this is especially a problem for transitive dependencies of libraries; consider:

- popular library A, version A1
- secondary library B, uses library A; version B1 references version A1
- application C, uses A directly, currently version A1, and also uses B, currently version B1

All good, everything works. Now imagine that library A gets updated for a bug fix or to add some new feature, so there's now a version A2; and someone updating application C decides to take that update - possibly for the fix, possibly for the new feature, or possibly just as a "keep the packages up to date" goal; library B hasn't been updated, so there's nothing new there, but we end up with a new version of C that uses A2 and B1. When the updated application C talks to A directly, it finds A2, and everything works - great! But now it tries to use library B, which is expecting A1, but instead it finds A2. On .NET Core, .NET 5/6/7/8 etc: this is fine. However, in .NET Framework, **this is not allowed** (at least, by default) - the version loaded needs to match *exactly* otherwise it fails with an assembly load exception. The only way to mitigate against this is by manually adding an "assembly binding redirect", which is a config entry that ways "when you see A, versions A1-A2, actually demand A2 regardless of what was requested". This is awkward, time consuming, and hard to get right - and it cannot be 100% reliably automated (there are known cases when the tooling won't spot this and warn / auto-fix it), meaning it can cause surprise failures.

Because of this, the guidance is "don't change the assembly version frequently", on the basis that if we minimize the number of assembly version changes to, say, majors: we're limiting the times when assembly-binding-redirect entries will need to be managed to those times when we're already thinking "major change, be careful".

You can see more about this topic on the library guidance here: https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/versioning#assembly-version - in particular see the links marked "strict assembly version loading" and "requires binding redirects", and the explicit guidance to only use the "major" in the AssemblyVersion, so 1.0.0, 1.0.1 and 1.1.0 would all have 1.0.0 as the AssemblyVersion.

**Comment by mgravell** [comment]
> This seems to be contradictory to how most other packages handle the versioning.

I strongly disagree here; I'm pretty sure this is *exactly* how most other packages handle versioning. Do you have some examples of libraries that work the other way?

**Comment by menaheme** [comment]
Thank you for the clear explanation!
I see now why assembly versions should be managed differently from nuget
package versions
