### ISSUE TITLE
Return null in service but throw a exception `No message returned from method.`

### ISSUE THREAD

**Issue by ElderJames** [protobuf-net/protobuf-net.Grpc#36]
I think the expected behavior  should be returning null in client side

**Comment by mgravell** [comment]
That's an interesting one, because protobuf has no concept of null, and no way to encode null. We could abuse headers, but I suspect that adds confusion because that would only work if both client and server knew about it, i.e. it would only work protobuf-net.Grpc to protobuf-net.Grpc

Frankly, I wonder if the best option is to leave it as-is. Thoughts?

**Comment by GoNextGroup** [comment]
Maybe, It's a solution to pass an "object" as a "null-value"?

**Comment by mgravell** [comment]
An outer message with an `optional` inner message works well. *That* I can encode.

**Comment by mgravell** [comment]
This is fundamentally not doable in the general case because protobuf *has no null*; I think the answer here is: "don't do that"
