### ISSUE TITLE
[Question] Is there a way to override handling of Guid types (or other types for that matter)

### ISSUE THREAD

**Issue by ronnyek** [protobuf-net/protobuf-net.Grpc#56]
Does there currently exist a way to with attributes or anything, exist the ability to manipulate what this lib uses for a specified type? It'd be nice if I could keep my pocos with a "guid" type, but have the grpc side of it just use string.

**Comment by mgravell** [comment]
Right now; no; your best bet would be a shadow property, i.e. instead of:

``` c#
[ProtoMember(42)]
public Guid Foo {get;set;}
```

you could have

``` c#
public Guid Foo {get;set;}
[ProtoMember(42)]
private Guid FooSerialized {
    get => /* your conversion here */
    set => Foo = /* your conversion here */
}
```

The upcoming v3 API includes new options for custom serializers, although this *specific* scenario is one that I'm still working on - but so far I've only considered how this applies to new custom types; I'd need to think about how this would apply to types with inbuilt behavior such as `Guid`.

And yes, I acknowledge that the way `Guid` is handled is bad. If I could go back 10+ years and give myself a dry slap and stern talking to: I would.

**Comment by ronnyek** [comment]
Honestly other than custom objects which seem like they already can be supported, the only other thing I think I'd probably need would be `DateTime`. Most of the things I'd want to send across the wire would suffice if guid and datetimes were supported with this stuff

**Comment by mgravell** [comment]
DateTime can be mapped to the well-known Timestamp type by adding
DataFormat=DataFormat.WellKnown on the member (in ProtoMember).

**Comment by ronnyek** [comment]
I think shadow properties will work for data contracts... and I could just make the services themselves take strings instead of guids... but currently I was defining my services with that... like `GetClient(Guid id)`

Would it be better when designing for grpc consumption to just avoid Guid (not sure at this point that this is an option)

**Comment by mgravell** [comment]
For now, probably yes.

**Comment by mgravell** [comment]
With protobuf-net v3, this is implemented via [`CompatibilityLevel`](https://protobuf-net.github.io/protobuf-net/compatibilitylevel) - anything over 300
